package org.java.core.day0817.db.entity;

import java.io.Serializable;
import java.util.Date;

public class EagleUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eagle_user.id
     *
     * @mbg.generated Fri Aug 17 09:07:35 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eagle_user.user_id
     *
     * @mbg.generated Fri Aug 17 09:07:35 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eagle_user.user_name
     *
     * @mbg.generated Fri Aug 17 09:07:35 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eagle_user.user_sex
     *
     * @mbg.generated Fri Aug 17 09:07:35 CST 2018
     */
    private Byte userSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eagle_user.user_birth_year
     *
     * @mbg.generated Fri Aug 17 09:07:35 CST 2018
     */
    private String userBirthYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eagle_user.user_birth_month
     *
     * @mbg.generated Fri Aug 17 09:07:35 CST 2018
     */
    private String userBirthMonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eagle_user.user_birth_day
     *
     * @mbg.generated Fri Aug 17 09:07:35 CST 2018
     */
    private String userBirthDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eagle_user.create_time
     *
     * @mbg.generated Fri Aug 17 09:07:35 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eagle_user.update_time
     *
     * @mbg.generated Fri Aug 17 09:07:35 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eagle_user
     *
     * @mbg.generated Fri Aug 17 09:07:35 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eagle_user.id
     *
     * @return the value of eagle_user.id
     *
     * @mbg.generated Fri Aug 17 09:07:35 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eagle_user.id
     *
     * @param id the value for eagle_user.id
     *
     * @mbg.generated Fri Aug 17 09:07:35 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eagle_user.user_id
     *
     * @return the value of eagle_user.user_id
     *
     * @mbg.generated Fri Aug 17 09:07:35 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eagle_user.user_id
     *
     * @param userId the value for eagle_user.user_id
     *
     * @mbg.generated Fri Aug 17 09:07:35 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eagle_user.user_name
     *
     * @return the value of eagle_user.user_name
     *
     * @mbg.generated Fri Aug 17 09:07:35 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eagle_user.user_name
     *
     * @param userName the value for eagle_user.user_name
     *
     * @mbg.generated Fri Aug 17 09:07:35 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eagle_user.user_sex
     *
     * @return the value of eagle_user.user_sex
     *
     * @mbg.generated Fri Aug 17 09:07:35 CST 2018
     */
    public Byte getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eagle_user.user_sex
     *
     * @param userSex the value for eagle_user.user_sex
     *
     * @mbg.generated Fri Aug 17 09:07:35 CST 2018
     */
    public void setUserSex(Byte userSex) {
        this.userSex = userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eagle_user.user_birth_year
     *
     * @return the value of eagle_user.user_birth_year
     *
     * @mbg.generated Fri Aug 17 09:07:35 CST 2018
     */
    public String getUserBirthYear() {
        return userBirthYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eagle_user.user_birth_year
     *
     * @param userBirthYear the value for eagle_user.user_birth_year
     *
     * @mbg.generated Fri Aug 17 09:07:35 CST 2018
     */
    public void setUserBirthYear(String userBirthYear) {
        this.userBirthYear = userBirthYear == null ? null : userBirthYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eagle_user.user_birth_month
     *
     * @return the value of eagle_user.user_birth_month
     *
     * @mbg.generated Fri Aug 17 09:07:35 CST 2018
     */
    public String getUserBirthMonth() {
        return userBirthMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eagle_user.user_birth_month
     *
     * @param userBirthMonth the value for eagle_user.user_birth_month
     *
     * @mbg.generated Fri Aug 17 09:07:35 CST 2018
     */
    public void setUserBirthMonth(String userBirthMonth) {
        this.userBirthMonth = userBirthMonth == null ? null : userBirthMonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eagle_user.user_birth_day
     *
     * @return the value of eagle_user.user_birth_day
     *
     * @mbg.generated Fri Aug 17 09:07:35 CST 2018
     */
    public String getUserBirthDay() {
        return userBirthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eagle_user.user_birth_day
     *
     * @param userBirthDay the value for eagle_user.user_birth_day
     *
     * @mbg.generated Fri Aug 17 09:07:35 CST 2018
     */
    public void setUserBirthDay(String userBirthDay) {
        this.userBirthDay = userBirthDay == null ? null : userBirthDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eagle_user.create_time
     *
     * @return the value of eagle_user.create_time
     *
     * @mbg.generated Fri Aug 17 09:07:35 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eagle_user.create_time
     *
     * @param createTime the value for eagle_user.create_time
     *
     * @mbg.generated Fri Aug 17 09:07:35 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eagle_user.update_time
     *
     * @return the value of eagle_user.update_time
     *
     * @mbg.generated Fri Aug 17 09:07:35 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eagle_user.update_time
     *
     * @param updateTime the value for eagle_user.update_time
     *
     * @mbg.generated Fri Aug 17 09:07:35 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}