package org.java.core.day0817.db.repository;

import org.java.core.day0817.db.entity.EagleUser;

public interface EagleUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eagle_user
     *
     * @mbg.generated Fri Aug 17 09:07:35 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eagle_user
     *
     * @mbg.generated Fri Aug 17 09:07:35 CST 2018
     */
    int insert(EagleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eagle_user
     *
     * @mbg.generated Fri Aug 17 09:07:35 CST 2018
     */
    int insertSelective(EagleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eagle_user
     *
     * @mbg.generated Fri Aug 17 09:07:35 CST 2018
     */
    EagleUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eagle_user
     *
     * @mbg.generated Fri Aug 17 09:07:35 CST 2018
     */
    int updateByPrimaryKeySelective(EagleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eagle_user
     *
     * @mbg.generated Fri Aug 17 09:07:35 CST 2018
     */
    int updateByPrimaryKey(EagleUser record);
}